### ISSUE TITLE
nightly environments are not up to date with master

### ISSUE THREAD

**Issue by Simpler1** [zoneminder-containers/zoneminder-base#51]
The latest changes to https://github.com/ZoneMinder/zoneminder are not available in the nightly environments

![image](https://github.com/zoneminder-containers/zoneminder-base/assets/5922273/71a15d11-7d21-4d0a-aa9b-6c826aa42443)

It seems to be at least a month behind.

Could this be related to the change from version to version.txt
https://github.com/ZoneMinder/zoneminder/commit/b20159d980fdb2b90c91541061c5ab011b73afa4

**Comment by alexyao2015** [comment]
Not sure what you're talking about. That screenshot shows a build from the most recent zoneminder commit. Looks like it's working fine to me.

**Comment by Simpler1** [comment]
No commits since about June 14th are in the nightly-1234 environment.

Look at line 286 of `/var/www/html/skins/classic/views/js/event.js`
In the zoneminder master, it is:
`  setCookie('zmEventScale'+eventData.MonitorId, scale);`

but in the nightly-1234 environment, it is:
`  setCookie('zmEventScale'+eventData.MonitorId, scale, 3600);`

That's just one example.

**Comment by alexyao2015** [comment]
That's probably something wrong with zoneminder then. You should consider reporting this to zoneminder if you believe their builds are broken. It's impossible for it to be building the wrong version since it just pulls from git directly. Nothing special is going on. 

https://github.com/zoneminder-containers/zoneminder-base/blob/2919b82cacf9a5407defaff9a55d9f54ee5aa654/Dockerfile#L18

**Comment by Simpler1** [comment]
If I run:
`git clone https://github.com/ZoneMinder/zoneminder.git .`
and then check the file above, line 286 has the correct change.
also `git log`, shows all of the commits.

These commits are not in the `nightly-1234` environment.  Do you see them in the `nightly-1234` environment?
